import type { AlertSender } from "../alert-authority/contracts";
import type { TaskVersionRef } from "../task-authority/task-version-ref";
import type { ModelToolAlertApplicationPort } from "./model-tool-journey-port";
import type { AlertSendPortResult, ExactLeaderSessionId } from "./model-tool-contracts";
import { DurableModelToolBindings } from "./durable-model-tool-bindings";
export class DurableModelToolAlertApplication implements ModelToolAlertApplicationPort {
  constructor(private readonly bindings: DurableModelToolBindings, private readonly sender?: AlertSender) {}
  async sendAlert(id: ExactLeaderSessionId, input: { target: import("./model-tool-contracts").AlertTarget; kind: "clarification" | "attention" | "announcement"; text: string; taskId?: string; taskVersion?: TaskVersionRef }): Promise<AlertSendPortResult> { const bound = await this.bindings.boundTeam(id); if (!bound) return { kind: "unavailable", reason: "no_active_team", message: "The exact leader Session is not bound to an active Team." }; if (input.target.kind === "team" && input.kind !== "announcement") return { kind: "refused", reason: "invalid_fanout", message: "Only announcement Alerts may target the whole Team." }; if (!this.sender) return { kind: "unavailable", reason: "team_authority_unavailable", message: "The Alert sender is not attached to this model-tool port." }; const lead = [...bound.config.members].reverse().find((m) => m.name === "team-lead" && m.isActive !== false); try { const result = await this.sender.sendAlert({ teamName: bound.teamName, from: "team-lead", to: input.target.kind === "team" ? "*" : input.target.name, kind: input.kind, text: input.text, taskId: input.taskId, taskVersion: input.taskVersion, expectedSender: lead?.membershipId ? { membershipId: lead.membershipId, sessionFile: bound.sessionFile } : undefined }); return { kind: "sent", alertId: result.alertId, acceptedRecipients: result.accepted.map((d) => d.recipient), failedRecipients: result.failures.map((f) => f.recipient) }; } catch (error) { const message = error instanceof Error ? error.message : String(error); return /recipient|not accepted by any current Team member/i.test(message) ? { kind: "refused", reason: input.target.kind === "team" ? "no_eligible_recipients" : "recipient_not_current", message } : { kind: "unavailable", reason: "team_authority_unavailable", message }; } }
}
